## 2.3 列表推导式

In [1]:
a = [i for i in range(1000) if i % 3 == 0 or i % 5 == 0]
print(a)
print(sum(a))

[0, 3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99, 100, 102, 105, 108, 110, 111, 114, 115, 117, 120, 123, 125, 126, 129, 130, 132, 135, 138, 140, 141, 144, 145, 147, 150, 153, 155, 156, 159, 160, 162, 165, 168, 170, 171, 174, 175, 177, 180, 183, 185, 186, 189, 190, 192, 195, 198, 200, 201, 204, 205, 207, 210, 213, 215, 216, 219, 220, 222, 225, 228, 230, 231, 234, 235, 237, 240, 243, 245, 246, 249, 250, 252, 255, 258, 260, 261, 264, 265, 267, 270, 273, 275, 276, 279, 280, 282, 285, 288, 290, 291, 294, 295, 297, 300, 303, 305, 306, 309, 310, 312, 315, 318, 320, 321, 324, 325, 327, 330, 333, 335, 336, 339, 340, 342, 345, 348, 350, 351, 354, 355, 357, 360, 363, 365, 366, 369, 370, 372, 375, 378, 380, 381, 384, 385, 387, 390, 393, 395, 396, 399, 400, 402, 405, 408, 410, 411, 414, 415, 417, 420, 423, 425, 426, 429, 430, 432, 435, 438, 440, 441, 444, 445, 447, 4

## 2.5 序列和可迭代对象拆包

In [ ]:
import os
# "_"表示虚拟变量，将不需要的值赋给它
_,filename = os.path.split('/home/runner/work/ProjectEuler/ProjectEuler/problem001.py')
print(filename)

problem001.py


In [5]:
list1 =[i for i in range(11)]
print(f"list1: {list1!r}")
a,b,*_,c = list1
print(f"a: {a}, b: {b}, c: {c}")

list1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a: 0, b: 1, c: 10


## 2.6 序列模式匹配

In [9]:
temp_list = [
    ['animal','tom',18,(1,1)],
    ['animal','jerry',19,(2,2)],
    ['human','li','si',20],
    ['plant','rose',2],
]
for item in temp_list:
    print(f'{item!r}')
    match item:
        case ['animal', name, age, (x, y)] if x==1:
            print(f'Animal: {name}, Age: {age}, Coordinates: ({x}, {y})')
        case ['human', name, surname, age]:
            print(f'Human: {name} {surname}, Age: {age}')
        case _:
            print('Unknown type')


['animal', 'tom', 18, (1, 1)]
Animal: tom, Age: 18, Coordinates: (1, 1)
['animal', 'jerry', 19, (2, 2)]
Unknown type
['human', 'li', 'si', 20]
Human: li si, Age: 20
['plant', 'rose', 2]
Unknown type


In [ ]:
for item in temp_list:
    print(f'{item!r}')
    match item:
        # Using a tuple pattern with a wildcard  to extract the type and coordinates
        case[str(type),*_,(int(x),int(y))]:
            print(f"Type: {type}, Coordinates: ({x}, {y})")

['animal', 'tom', 18, (1, 1)]
Type: animal, Coordinates: (1, 1)
['animal', 'jerry', 19, (2, 2)]
Type: animal, Coordinates: (2, 2)
['human', 'li', 'si', 20]
['plant', 'rose', 2]


## 2.7 切片

### 2.7.2 切片对象

#### 步距

In [ ]:
temp_list = [i for i in range(20) if i % 2 == 0]
print(f'temp_list: {temp_list!r}')

a = temp_list[::-1]
print(f'倒序: {a!r}')
a = temp_list[3:6:2]
print(f'切片+步距: {a!r}')

temp_list: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
倒序: [18, 16, 14, 12, 10, 8, 6, 4, 2, 0]
切片: [6, 10]


#### 切片命名

In [7]:
temp_list = ['tom', 'jerry', 'rose',2,3,5,5,6]
NAME = slice(0,3)
NUMBER = slice(3,7)
print(f'NAME: {temp_list[NAME]!r}')
print(f'NUMBER: {temp_list[NUMBER]!r}')

NAME: ['tom', 'jerry', 'rose']
NUMBER: [2, 3, 5, 5]


### 2.7.4 为切片赋值

In [14]:
temp_list2 = [i for i in range(20)]
print(f'temp_list2: {temp_list2!r}')
temp_list2[5:7] = [100,200]
print(f'更新后的temp_list2: {temp_list2!r}')
temp_list2[2:17] = [0]
print(f'更新后的temp_list2: {temp_list2!r}')

temp_list2: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
更新后的temp_list2: [0, 1, 2, 3, 4, 100, 200, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
更新后的temp_list2: [0, 1, 0, 17, 18, 19]


## 2.9 list.sort 和 sorted

In [ ]:
temp_list = [0,4,56,3,1,6,3,87,35]
temp_list.sort(reverse=False)# 默认升序,直接修改原列表，也可以传参key，例如lambda x:x
print(temp_list)

[0, 1, 3, 3, 4, 6, 35, 56, 87]


In [ ]:
temp_list = [0,4,56,3,1,6,3,87,35]
# key 参数指定排序规则，接收序列的每一个迭代元素作为参数，返回一个值用于比较
a = sorted(temp_list, reverse=True,key=lambda x: str(x)[-1])  # 根据最后一位数降序，返回新列表
print(f'根据最后一位数降序: {a!r}')  # 返回新列表，不修改原列表

降序: [87, 56, 6, 35, 4, 3, 3, 1, 0]


## 2.10 当列表不适用时

### 2.10.1 数组

In [31]:
from array import array
from random import random
# 创建一个整数类型的数组
a = array('d',[random() for _ in range(100000)])
with open('test.bin', 'wb') as f:
    a.tofile(f)  # 将数组写入二进制文件
print(a[-1])

0.712491356053769


In [32]:
with open('test.bin', 'rb') as f:
    b = array('d')  # 创建一个空的数组
    b.fromfile(f, 100000)  # 从文件中读取100000个元素
print(b[-1])  # 打印最后一个元素

0.712491356053769


In [20]:
a[0] = a[-1]

In [ ]:
a[0]==a[-1] # 数组处理很快 

True

### 2.10.2 memoryview

### 2.10.3 NumPy

In [33]:
import numpy as np
a=np.arange(12)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [26]:
a.shape

(12,)

In [30]:
a.shape = (3, 4)  # 改变数组形状
print(a)
print("########################")
print(a[:,1])  # 打印第二列
print("########################")
print(a.transpose())  # 转置数组

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
########################
[1 5 9]
########################
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
f = np.array([random() for _ in range(100000)])
print(f[-3:-1])
np.save('test.npy', f)  # 保存为npy文件

[0.89794533 0.1079549 ]


In [39]:
f2 = np.load('test.npy','r+')  # 从npy文件加载
print(f2[-3:-1])  # 打印最后两个元素
f2 *=0.5
print(f2[-3:-1])  # 打印最后两个元素，修改了原数组

[0.89794533 0.1079549 ]
[0.44897266 0.05397745]


### 2.10.4 双端队列和其他队列

#### deque

In [42]:
from collections import deque
# 创建一个双端队列
d = deque([1, 2, 3, 4, 5])
# 在队列的右侧添加元素
d.append(6)
print(f'添加元素后: {d!r}')
# 在队列的左侧添加元素
d.appendleft(0)
print(f'添加元素后: {d!r}')
# 从队列的右侧移除元素
d.pop()
print(f'移除元素后: {d!r}')
# 从队列的左侧移除元素
d.popleft()
print(f'移除元素后: {d!r}')
# extend 队列
d.extend([7, 8, 9])
print(f'扩展后: {d!r}')
# extendleft 队列
d.extendleft([-2, -1])  # 注意，extendleft会反向添加
print(f'扩展后: {d!r}')
# rotate 队列
d.rotate(2)  # 向右旋转2个位置
print(f'旋转后: {d!r}')
# 反转队列
d.reverse()
print(f'反转后: {d!r}')
# 清空队列
d.clear()
print(f'清空后: {d!r}')

添加元素后: deque([1, 2, 3, 4, 5, 6])
添加元素后: deque([0, 1, 2, 3, 4, 5, 6])
移除元素后: deque([0, 1, 2, 3, 4, 5])
移除元素后: deque([1, 2, 3, 4, 5])
扩展后: deque([1, 2, 3, 4, 5, 7, 8, 9])
扩展后: deque([-1, -2, 1, 2, 3, 4, 5, 7, 8, 9])
旋转后: deque([8, 9, -1, -2, 1, 2, 3, 4, 5, 7])
反转后: deque([7, 5, 4, 3, 2, 1, -2, -1, 9, 8])
清空后: deque([])
